### ISSUE TITLE
Do not request microphone permission on first load

### ISSUE THREAD

**Issue by poshaughnessy** [SamsungInternet/samsung-shop#1]
Hi. It is not best practice to request permission immediately on page load - see [for example](https://blog.chromium.org/2017/10/chrome-63-beta-dynamic-module-imports_27.html):

_"...developers often show [permissions prompts] without considering whether the user has the appropriate context to grant the permission. This results in a distracting user experience, and users ignore or temporarily dismiss these permission prompts more than 90% of the time."_

@winstonchen would it be possible please to only enable the web audio part of the demo after some user interaction to indicate that they want to use it?

**Comment by winstonchen** [comment]
The audio portion now starts when the user interacts with the page. I added an event listener for touchstart and remove this event after the first time the page begins to listen. Afterwords, the page continuously listens.
